name: importee
base: core22
version: '0.1.0'
summary: Python import checker with Rust backend
description: |
  Importee checks Python import ordering rules and enforces dependencies
  in your Python projects. Uses Rust for parsing and analysis.

title: Importee
license: BSD-2-Clause
contact: nathan.duboisset@gmail.com
website: https://github.com/NathanDuboisset/importee
source-code: https://github.com/NathanDuboisset/importee
issues: https://github.com/NathanDuboisset/importee/issues

grade: stable
confinement: strict

apps:
  importee:
    command: bin/importee
    plugs:
      - home
      - removable-media

parts:
  importee:
    plugin: python
    source: .
    build-packages:
      - cargo
      - rustc
      - libssl-dev
      - pkg-config
    stage-packages:
      - libssl3
    python-packages:
      - maturin
    override-build: |
      # Install Rust toolchain
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      export PATH="$HOME/.cargo/bin:$PATH"
      
      # Install maturin and build the package
      pip install maturin[patchelf]
      maturin build --release --interpreter python3
      
      # Install into a fresh venv in the install directory
      python3 -m venv $CRAFT_PART_INSTALL
      $CRAFT_PART_INSTALL/bin/pip install --upgrade pip
      $CRAFT_PART_INSTALL/bin/pip install target/wheels/*.whl
      
      # Fix shebangs to use the snap's python
      sed -i '1s|^#!.*python.*|#!/usr/bin/env python3|' $CRAFT_PART_INSTALL/bin/*
    stage:
      - bin
      - lib
      - pyvenv.cfg

